<?php

namespace BitApps\Crm\Services;

use BitApps\Crm\Config;
use BitApps\Crm\Constants\HookKeys;
use BitApps\Crm\Deps\BitApps\WPKit\Hooks\Hooks;
use BitApps\Crm\Model\Invoice;
use BitApps\Crm\Views\Head;

/**
 * Serves the public (no-login) shareable invoice page.
 *
 * Propovoice-style delivery: the page is an HTML shell that mounts the SAME
 * React bundle the admin uses — main.tsx sees the `publicInvoice` server
 * variable and renders the public invoice app instead of the admin router, so
 * the UI stays fully consistent. This class only validates the share token,
 * enqueues the bundle and prints the shell; data and the pay action flow
 * through the token-guarded public REST endpoints.
 *
 * URL shape: home_url('/bit-crm/invoice?id=<id>&token=<token>'), generated by
 * InvoiceShareTokenService::getPublicInvoiceUrl(). The path is matched
 * directly against the request URI on template_redirect (priority 0, before
 * WordPress's canonical/404-guess redirects) — no rewrite rules, so no flush
 * is needed and any permalink setting works.
 */
class InvoicePublicPageService
{
    public const PATH = Config::PUBLIC_URL_PREFIX . '/invoice';

    /**
     * template_redirect callback — renders the app shell and exits when the
     * request targets the share-link path and the token matches.
     */
    public function maybeRenderPage(): void
    {
        if (!$this->isPublicInvoiceRequest()) {
            return;
        }

        /*
         * No nonce by design: this page is opened by an anonymous visitor from
         * an emailed share link — there is no session to bind a nonce to. The
         * per-invoice token (hash_equals below) is the credential, mirroring
         * WooCommerce's own order-pay `key` handling. Read-only GET, no state
         * change happens here.
         */
        $invoiceId = isset($_GET['id']) ? absint(wp_unslash($_GET['id'])) : 0; // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- token-authenticated public page, see above
        $tokenParam = InvoiceShareTokenService::TOKEN_QUERY_PARAM;
        $token = isset($_GET[$tokenParam]) ? sanitize_text_field(wp_unslash($_GET[$tokenParam])) : ''; // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- token-authenticated public page, see above

        $invoice = $invoiceId > 0 ? Invoice::findOne(['id' => $invoiceId]) : null;

        if (empty($invoice) || $invoice->is_trash || !(new InvoiceShareTokenService())->isValidToken($invoice, $token)) {
            status_header(404);
            nocache_headers();
            wp_die(
                esc_html__('Invoice not found.', 'bit-crm-sales-marketing-automation'),
                esc_html__('Invoice not found', 'bit-crm-sales-marketing-automation'),
                ['response' => 404]
            );
        }

        $this->enqueueAppAssets((int) $invoice->id, (string) $invoice->token);

        status_header(200);
        nocache_headers();
        header('X-Robots-Tag: noindex, nofollow');

        $title = \sprintf(
            // translators: %s: invoice number
            __('Invoice %s', 'bit-crm-sales-marketing-automation'),
            $invoice->invoice_prefix . '-' . $invoice->id
        );

        echo '<!DOCTYPE html><html ';
        language_attributes();
        echo '><head>';
        echo '<meta charset="' . esc_attr(get_bloginfo('charset')) . '">';
        echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
        echo '<meta name="robots" content="noindex, nofollow">';
        echo '<title>' . esc_html($title) . '</title>';
        wp_head();
        echo '</head><body class="bit-crm-public-invoice">';
        echo '<noscript>' . esc_html__('You need to enable JavaScript to view this invoice.', 'bit-crm-sales-marketing-automation') . '</noscript>';
        echo '<div id="bit-crm-public-invoice-root"></div>';
        wp_footer();
        echo '</body></html>';

        exit;
    }

    /**
     * script_loader_tag filter — the Vite bundle is an ES module. Mirrors
     * Views\HtmlTagModifier, which only runs for admin requests.
     *
     * @param mixed $html
     */
    public function updateScriptAttributes($html)
    {
        $slug = Config::SLUG;
        $typeAttribute = 'type="module"';

        $keys = [
            '-vite-client-helper-MODULE-js',
            '-vite-client-MODULE-js',
            '-index-MODULE-js',
        ];

        foreach ($keys as $key) {
            $handleId = 'id="' . $slug . $key . '"';

            if (strpos($html, $handleId) !== false) {
                $html = str_replace($handleId, $handleId . ' ' . $typeAttribute, $html);
            }
        }

        return $html;
    }

    /**
     * Removes theme / block styles so they cannot fight the app's own styles.
     */
    public function dequeueThemeAssets(): void
    {
        wp_dequeue_style('style');
        wp_deregister_style('style');
        wp_dequeue_style('child-style');
        wp_deregister_style('child-style');
        wp_dequeue_style('wp-block-library');
        wp_dequeue_style('wp-block-library-theme');
        wp_dequeue_style('wc-blocks-style');
        wp_dequeue_style('classic-theme-styles');
        wp_dequeue_style('global-styles');
    }

    /**
     * True when the request path is the public invoice page
     * (`/bit-crm/invoice`, honoring subdirectory installs).
     */
    private function isPublicInvoiceRequest(): bool
    {
        $requestUri = isset($_SERVER['REQUEST_URI']) ? sanitize_url(wp_unslash($_SERVER['REQUEST_URI'])) : '';
        $requestPath = (string) wp_parse_url($requestUri, PHP_URL_PATH);
        $homePath = (string) (wp_parse_url(home_url('/'), PHP_URL_PATH) ?: '/');

        return untrailingslashit($requestPath) === untrailingslashit($homePath . self::PATH);
    }

    /**
     * Enqueues the same app bundle the admin loads (same handles, so the
     * module-type filter applies), with public-safe server variables.
     */
    private function enqueueAppAssets(int $invoiceId, string $token): void
    {
        $slug = Config::SLUG;
        $version = Config::VERSION;
        $scriptHandle = $slug . '-index-MODULE';

        Hooks::addAction('wp_enqueue_scripts', [$this, 'dequeueThemeAssets'], PHP_INT_MAX);
        Hooks::addFilter('script_loader_tag', [$this, 'updateScriptAttributes'], 0);

        wp_enqueue_style($slug . '-googleapis-PRECONNECT', 'https://fonts.googleapis.com', [], $version);
        wp_enqueue_style($slug . '-gstatic-PRECONNECT-CROSSORIGIN', 'https://fonts.gstatic.com', [], $version);
        wp_enqueue_style($slug . '-font', Head::FONT_URL, [], $version);

        if (Config::getEnv('DEV')) {
            wp_enqueue_script($slug . '-vite-client-helper-MODULE', Config::getEnv('DEV_URL') . '/src/config/devHotModule.js', [], null);
            wp_enqueue_script($slug . '-vite-client-MODULE', Config::getEnv('DEV_URL') . '/@vite/client', [], null);
            wp_enqueue_script($scriptHandle, Config::getEnv('DEV_URL') . '/src/main.tsx', [], null);
        } else {
            $codeName = Config::get('BUILD_CODE_NAME');
            // phpcs:ignore WordPress.WP.EnqueuedResourceParameters.NoExplicitVersion -- hashed via build code name, mirrors Head::addHeadScripts()
            wp_enqueue_script($scriptHandle, Config::get('ASSET_URI') . "/main-{$codeName}.js", [], null); // WARNING: Do not add version in production, it may cause unexpected behavior.

            if (!Head::enqueueEntryStyles($slug . '-styles', 'src/main.tsx')) {
                wp_enqueue_style($slug . '-styles', Config::get('ASSET_URI') . "/main-{$slug}-ba-assets-{$codeName}.css", null, $version, 'screen');
            }
        }

        wp_localize_script($scriptHandle, Config::VAR_PREFIX, $this->configVariables($invoiceId, $token));
    }

    /**
     * Same server variables the admin app receives, minus admin-only context,
     * plus the invoice the page was opened for. The REST client deliberately
     * sends NO X-WP-Nonce on the public routes (`skipNonce` in request.ts):
     * WordPress 403s any request carrying a stale nonce — e.g. one baked into
     * a cached copy of this page — before the share-token check runs, while a
     * nonce-less request is simply treated as unauthenticated and passes.
     */
    private function configVariables(int $invoiceId, string $token): array
    {
        $frontendVars = Head::createConfigVariable();

        $frontendVars['capabilities'] = [];
        $frontendVars['settings'] = null;
        $frontendVars['currentUserId'] = 0;
        $frontendVars['publicInvoice'] = [
            'id'    => $invoiceId,
            'token' => $token,
        ];

        return Hooks::applyFilter(HookKeys::PUBLIC_INVOICE_CONFIG_VARIABLES, $frontendVars);
    }
}
